# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: crane_arm_serial
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - jointb
    - joint1
    - joint2
    - arm_3e
    - jointA2e
    - jointA1e
    - joint_t3
    - joint_t4
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  # - name: crane_arm_serial
  #   action_ns: follow_joint_trajectory
  #   default: True
  #   type: FollowJointTrajectory
  #   joints:
  #     - jointb
  #     - joint1
  #     - joint2
  - name: actuator_slew_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - jointb
  - name: actuator_base_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      # - jointA1
      - jointA1e
  - name: actuator_jib_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      # - jointA2
      - jointA2e
  - name: arm_extension_controller
    action_ns: follow_joint_trajectory
    default: False
    type: FollowJointTrajectory
    joints:
      - arm_3e
crane_arm_serial:
  type: position_controllers/JointTrajectoryController
  joints:
    - jointb
    - joint1
    - joint2
  gains:
    jointb:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_3e:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
actuator_slew_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - jointb
  gains:
    jointA1e:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
actuator_base_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    # - jointA1
    - jointA1e
  gains:
    jointA1e:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
actuator_jib_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    # - jointA2
    - jointA2e
  gains:
    jointA2e:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_extension_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_3e
  gains:
    arm_3e:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
